### PR TITLE
Net::LDAP::DN - Retain trailing spaces in RDN values in DNs

### PR DESCRIPTION
**Pull request by TomSellers**
`Net::LDAP::DN.each_pair` and `Net::LDAP::DN.to_a` are stripping trailing spaces in the values they return. The comment for `each_pair` refers to [RFC 2253 Section 3](https://www.rfc-editor.org/rfc/rfc2253#section-3) for the rules on parsing the DN into key value pairs. It allows for spaces in values.  In [Section 2.4](https://www.rfc-editor.org/rfc/rfc2253#section-2.4), which is just prior, it states how to escape leading and trailing spaces in values.

`Net::LDAP::DN` retains leading and trailing spaces and escapes as expected when calling `to_s` however when calling `each_pair` or `to_a` it is removing the trailing spaces.

For example:
Original data: `CN=Foo.bar.baz, OU=Foo   \ ,OU=\  Bar, O=Baz`
`to_s`  output:  `CN=Foo.bar.baz, OU=Foo   \ ,OU=\  Bar, O=Baz`
`to_a` output:
```
CN: 'Foo.bar.baz'
OU: 'Foo'                <- This should be 'Foo    '
OU: '  Bar'
O: 'Baz'
```

This PR contains changes to change this behavior and tests to verify the results.

## Before changes

```ruby
irb
irb(main):001:0> require 'net/ldap'
=> true
irb(main):002:0> require 'net/ldap/dn'
=> true

# Check version
irb(main):003:0> Net::LDAP::VERSION
=> "0.17.1"

# create the object using the test string
irb(main):004:0> test = Net::LDAP::DN.new('CN=Foo.bar.baz, OU=Foo   \ ,OU=\  Bar, O=Baz')
=> #<Net::LDAP::DN:0x000000015bb4b138 @dn="CN=Foo.bar.baz, OU=Foo   \\ ,OU=\\  Bar, O=Baz">

# verify that the spaces exist and are escaped as expected in `to_s`
irb(main):005:0> test.to_s
=> "CN=Foo.bar.baz, OU=Foo   \\ ,OU=\\  Bar, O=Baz"

# verify that the values returned by `to_a` retain the spaces
# Failed - missing trailing spaces in `Foo    `
irb(main):007:0> test.to_a
=> ["CN", "Foo.bar.baz", "OU", "Foo", "OU", "  Bar", "O", "Baz"]

# verify that the values returned by each_pair retain the spaces
# Failed - missing trailing spaces in `Foo    `
irb(main):006:0> test.each_pair { |k, value| puts(k +": '" + value +"'") }
CN: 'Foo.bar.baz'
OU: 'Foo'
OU: '  Bar'
O: 'Baz'
=> nil

```
## After changes

```ruby
$ irb
irb(main):001:0> require 'net/ldap'
=> true
irb(main):002:0> require 'net/ldap/dn'
=> true

# create the object using the test string
irb(main):005:0> test = Net::LDAP::DN.new('CN=Foo.bar.baz, OU=Foo   \ ,OU=\  Bar, O=Baz')
=> #<Net::LDAP::DN:0x000000012fad3d58 @dn="CN=Foo.bar.baz, OU=Foo   \\ ,OU=\\  Bar, O=Baz">

# verify that the spaces exist and are escaped as expected in `to_s`
irb(main):006:0> test.to_s
=> "CN=Foo.bar.baz, OU=Foo   \\ ,OU=\\  Bar, O=Baz"

# verify that the values returned by `to_a` retain the spaces
irb(main):008:0> test.to_a
=> ["CN", "Foo.bar.baz", "OU", "Foo    ", "OU", "  Bar", "O", "Baz"]

# verify that the values returned by each_pair retain the spaces
irb(main):007:0> test.each_pair { |k, value| puts(k +": '" + value +"'") }
CN: 'Foo.bar.baz'
OU: 'Foo    '
OU: '  Bar'
O: 'Baz'
=> nil
```

### CODE REVIEW

**Comment by TomSellers** [comment]
Note, the `jruby-9.2` test failure is due to that version of JRuby being too old to work with bundler.

```
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.3.26. Try installing it with `gem install bundler -v 2.3.26`
	bundler requires Ruby version >= 2.6.0. The current ruby version is 2.5.8.0.
1
Error: Process completed with exit code 1.
``

**Comment by TomSellers** [comment]
@HarlemSquirrel Would it be possible to have this fix included in the next release?

**Comment by HarlemSquirrel** [comment]
@TomSellers Thanks for this. It looks great! Could you please update the branch from master so CI can run?

**Review by HarlemSquirrel — CHANGES_REQUESTED** [review]
Code looks good to me. Please update from the latest master branch so CI can run.

**Comment by TomSellers** [comment]
@HarlemSquirrel Triggered, waiting on approval.

**Review by HarlemSquirrel — APPROVED** [review]

**Pull request merged**
