### PR TITLE
Add support to use SNI

### PR DESCRIPTION
**Pull request by jpdasma**
Related to https://github.com/ruby-ldap/ruby-net-ldap/issues/405

### CODE REVIEW

**Comment by jpdasma** [comment]
I'm thinking if it's better to have an option to use SNI or just always enable it?

The default `openssl` binary uses SNI by default.

**Comment by jpdasma** [comment]
I'll fix the broken tests first.

**Comment by jpdasma** [comment]
The failing test should be fixed now. I also tested with `db.debian.org:636`.

From some of my readings, SNI is an optional TLS extension, so it should be safe to be enabled by default.

Although we might still want to test it to other LDAP server with TLS.

**Comment by jpdasma** [comment]
@HarlemSquirrel based on my tests, I think this should be safe to merge. I didn't encountered any issues with OpenLDAP and Windows LDAP.

**Review by HarlemSquirrel — APPROVED** [review]

**Comment by HarlemSquirrel** [comment]
Thank you!

**Pull request merged**
