### PR TITLE
Handle nil value in GetbyteForSSLSocket::getbyte

### PR DESCRIPTION
**Pull request by tmccombs**
Related to  #266

### CODE REVIEW

**Comment by tmccombs** [comment]
I'm not sure that this will completely fix #266. This might just result in a different error. But it seems to me that this should be the correct behavior, and it looks like at least some of the places that call this do expect to get nil back sometimes.

**Comment by schaary** [comment]
thanks for the PR! Currently I am not able to push a new release, because I am on vacation an fortunately far away from my computer. I am back at the beginning of August.

**Comment by dawid-sklodowski** [comment]
Any chances for merging this pull request in?

**Comment by dklotz** [comment]
@schaary @mtodd Any chance a maintainer could look at this and #308 ?

**Comment by tmccombs** [comment]
Any progress on this?

**Comment by cjs** [comment]
This PR fixed an issue for us when interfacing with the [Duo Authentication LDAP proxy](https://duo.com/docs/authproxy-reference). It seems to be low risk and would be helpful if merged.

**Comment by felixbuenemann** [comment]
I also ran into this bug when using haproxy as LDAPS proxy in front of a pool of AD LDAP servers and haproxy dropped the connection because none of the backendas where healthy.

**Comment by Greg-Myers-SB** [comment]
@HarlemSquirrel Would it be possible to get a review of this fix please?
I believe a few forks exist solely to use this patch.

**Review by HarlemSquirrel — APPROVED** [review]
LGTM

**Pull request merged**
